### ISSUE TITLE
'#' should be reserved for page title

### ISSUE THREAD

**Issue by berkas1** [bigclownlabs/bc-website#3]
Use of first level headline ('#' in markdown) should be reserved for page titles only.

- this is common use of first level headlines
- it does not look nice when page title is smaller than subtitles

**Comment by hubpav** [comment]
Actually, we set the title in YAML front matter. We have not yet finalized the CSS for the title - I agree it, it must uses biggest font :-) So it is more about semantics, since we will never use the single `#` in Markdown for the title setting but more for the first level of chapters. What do you think?
